In [1]:
import pandas as pd

In [2]:
export = pd.read_csv('export.csv')

In [3]:
export.head(n=10)

,customer_id,account_id,ed_id,event_name,event_timestamp,journey_steps_until_end
0,-784961211,1773350293,12,application_web_approved,2023-03-22T08:45:22.000Z,1
1,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,2
2,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,3
3,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,4
4,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,5
5,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,6
6,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,7
7,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,8
8,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,9
9,-784961211,1773350293,19,application_web_view,2023-03-22T13:32:10.000Z,10

In [4]:
import matplotlib as plt

In [ ]:
hist =